# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.15.20"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/seddonym/import-linter
    rev: v2.13
    hooks:
      - id: import-linter
        additional_dependencies: [".[toml]"]
        language: python
  - repo: https://github.com/python-poetry/poetry
    rev: 2.4.1
    hooks:
      - id: poetry-check
        args: ["--lock"]
